### PR TITLE
Jwt support for cloudflare access

### PR DESCRIPTION
**Pull request by felipebn**
This PR intents to expand the support of JWT authentication to Cloudflare Access service.

Changes summary:

- Fixing configuration parsing
    - Fixup includes test for claims parsing
- Adding specific validation for audience due to the JWT spec allowing the audience claim to be a an array
- Removing `convey` in JWT tests to align with Grafana's contribution guideline
- Adding testing with Cloudflare Access test tokens and keys

### CODE REVIEW

**Comment by felipebn** [comment]
Hi @jregistr ,

First, good work you and @ryantxu put into this!

I'm looking into adding support to Cloudflare Access and what you already had was just a few steps away of allowing that therefore I'm looking to contribute with you guys to get it into Grafana's mainline.

I will probably add some more contributions like:

- configuration tests :heavy_check_mark:  
- test data relocation (like it is done in `pkg/setting`) :heavy_check_mark:  

Looking forward to hear from you!

**Comment by jregistr** [comment]
Amazing!
Thank you for this @felipebn
Have you tried this change against Google IAP?

**Comment by felipebn** [comment]
Just with the unit tests that were already there.

I’m going to setup a test and give it try.

**Comment by felipebn** [comment]
Hey @jregistr !

I finally had time to setup Google IAP and test, and it looks good:


iap

**Review by jregistr — APPROVED** [review]

**Pull request merged**
